#!/usr/bin/env bash
#nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
sudo service nginx reload
