#!/usr/bin/env bash
#redirect to another page as root
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello Holberton" > /usr/share/nginx/html/index.html
sudo sed -i "26 i \	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
