#!/usr/bin/env bash
#french 404
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/french_404.html
notfound="error_page 404 /french_404.html;\n\tlocation = /french_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "s|\#error_page 404 /404.html;|$notfound|" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service reload
