#!/usr/bin/env bash
#french 404
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i "43 i \ rewrite ^/error_page 404/custom_404.html;location = /custom_404.html{root /usr/share/nginx/html;internal;}" /etc/nginx/sites-available/default
sudo service nginx restart
