#!/usr/bin/env bash
#haproxy installation for load balancer
sudo apt-get update
sudo apt-get -y install haproxy
sudo service haproxy start
sudo echo $'frontend http-in\n\tbind *:80\n\tdefault_backend servers' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo $'backend servers\n\tbalance roundrobin\n\tserver 118-web-01 142.44.167.33:80 check\n\tserver 118-web-02 144.217.246.254:80 check' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
