#!/usr/bin/env bash
#haproxy installation for load balancer
sudo apt-get update
sudo apt-get install haproxy
sudo service haproxy start
sudo echo $'frontend http-in\n\tbind *:80\n\tdefault_backend servers' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo $'backend servers\n\tbalance roundrobin\n\tserver 110-web-01 144.217.245.116\n\tserver 110-web-02 54.91.123.178' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
