#!/usr/bin/env bash
#haproxy installation for load balancer
sudo apt-get update
sudo apt-get -y install haproxy
sudo service haproxy start
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo echo $'frontend http-in\n\tbind *:80\n\tdefault_backend servers' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo sed -i "1 i\http\n\tstats enable\n\tstats uri /haproxy?stats\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 118-web-01 142.44.167.33:80 check\n\tserver 118-web-02 144.217.246.254:80 check\n" /etc/haproxy/haproxy.cfg
sudo service haproxy start
