#!/usr/bin/env bash
#The MySQL dump must contain all your MySQL databases
PASWRD="$1"
NOW=$(date +"%d-%m-%Y")
mysqldump -u root "-p$PASWRD" --opt --all-databases > backup.sql
tar -czvf "$NOW.tar.gz" backup.sql
