#!/usr/bin/env bash
# debug run nginx as nginx
pkill apache2
sudo service nginx stop
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo service nginx start
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo service nginx restart
